version: '3'

services:
  rosserial:
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    tty: true
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://10.0.0.111:11311
    command:
      - /opt/ros/noetic/bin/rosrun
      - rosserial_python
      - serial_node.py
      - _port:=/dev/mowgli
      - _baud:=115200
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    privileged: true
  gps:
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    restart: unless-stopped
    tty: true
    environment:
      - ROS_MASTER_URI=http://10.0.0.111:11311
    command:
      - /entrypoint.sh
      - /home/ubuntu/scripts/start_gps.sh
    volumes:
      - ./mower_params:/home/ubuntu/mower_params:ro
      - ./params:/home/ubuntu/open_mower_ros/src/open_mower/params:ro
      - ./config/om:/home/ubuntu/open_mower_ros/src/open_mower/config:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    privileged: true