version: '3'

services:
  web:
    image: nginx
    restart: unless-stopped
    ports:
      - 4005:80
    volumes:
      - ./web:/usr/share/nginx/html:ro
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"
      - 9001:9001
  roscore:
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    pull_policy: always
    tty: true
    restart: unless-stopped
    command:
      - /opt/ros/noetic/bin/roscore
    volumes:
      - ./ros:/home/ubuntu/.ros/
      - /etc/timezone:/etc/timezone:ro
    privileged: true
  rosserial:
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    pull_policy: always
    tty: true
    restart: unless-stopped
    command:
      - /opt/ros/noetic/bin/rosrun
      - rosserial_python
      - serial_node.py
      - _port:=/dev/mowgli
      - _baud:=115200
    volumes:
      - ./ros:/home/ubuntu/.ros/
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    privileged: true
    depends_on:
      - gps-relay
      - mowgli-relay
      - imu-relay
  mowgli:
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo
    network_mode: host
    pull_policy: always
    restart: unless-stopped
    tty: true
    volumes:
      - ./mower_params:/home/ubuntu/mower_params:ro
      - ./params:/home/ubuntu/MowgliRover/src/Mowgli-open_mower_ros/src/open_mower/params:ro
      - ./ros:/home/ubuntu/.ros/
      - ./config/mowgli/mowgli_config.sh:/home/ubuntu/MowgliRover/src/mowgli/config/mowgli_config.sh:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    privileged: true
    depends_on:
      - roscore
      - rosserial
  gps-relay:
    image: alpine/socat
    command: "pty,link=/dev/gps,ignoreof,waitslave,group-late=100,user-late=1000,raw,mode=660,echo=0 tcp:${MOWER_IP}:4002"
    restart: unless-stopped
    privileged: true
    volumes:
    - /dev:/dev
  mowgli-relay:
    image: alpine/socat
    command: "pty,link=/dev/mowgli,ignoreof,waitslave,group-late=100,user-late=1000,raw,mode=660,echo=0 tcp:${MOWER_IP}:4001"
    restart: unless-stopped
    privileged: true
    volumes:
    - /dev:/dev
  imu-relay:
    image: alpine/socat
    command: "pty,link=/dev/debug,ignoreof,waitslave,group-late=100,user-late=1000,raw,mode=660,echo=0 tcp:${MOWER_IP}:4003"
    restart: unless-stopped
    privileged: true
    volumes:
    - /dev:/dev
