version: '3'

services:
  rosserial:
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo-arm64
    network_mode: host
    tty: true
    restart: unless-stopped
    environment:
      ROS_IP: ${MOWER_IP}
      ROS_MASTER_URI: http://${ROS_IP}:11311
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    command:
      - /opt/ros/noetic/bin/rosrun
      - rosserial_server
      - serial_node
      - _port:=/dev/mowgli
      - _baud:=115200
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    privileged: true
  gps:
    image: ghcr.io/cedbossneo/mowgli-docker:cedbossneo-arm64
    network_mode: host
    restart: unless-stopped
    tty: true
    environment:
      ROS_IP: ${MOWER_IP}
      ROS_MASTER_URI: http://${ROS_IP}:11311
    command:
      - /home/ubuntu/scripts/start_gps.sh
    volumes:
      - ./mower_params:/home/ubuntu/mower_params:ro
      - ./params:/home/ubuntu/open_mower_ros/src/open_mower/params:ro
      - ./config/om:/home/ubuntu/open_mower_ros/src/open_mower/config:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
    privileged: true