name: Cedbossneo

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron:  '30,0 * * * *'
  workflow_dispatch:
    inputs:
      ignoreCommits:
        description: 'Ignore commits (y/n)?'
        required: true
        default: 'y'
  push:
    branches: [ "cedbossneo" ]
    paths:
      - docker/openmower/**
      - .github/workflows/docker-publish-cedbossneo.yml


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    strategy:
      matrix:
        runs-on: [ buildjet-4vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204-arm ]
        include:
          - tag: amd64
            runs-on: buildjet-4vcpu-ubuntu-2204
          - tag: arm64
            runs-on: buildjet-4vcpu-ubuntu-2204-arm
    name: Build - cedbossneo - ${{matrix.tag}}
    runs-on: ${{matrix.runs-on}}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        if: steps.check.outputs.needs-updating == 'true' || github.event.inputs.ignoreCommits == 'y'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Check if update available
        id: check
        uses: cedbossneo/container-image-updater-action@v1.0.8
        with:
          base-image: ghcr.io/clemenselflein/open_mower_ros:main
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cedbossneo-${{matrix.tag}}
          platform: linux/${{ matrix.tag }}
          image-reg-username: ${{ github.actor }}
          image-reg-password: ${{ secrets.SECRET_TOKEN }}
      - name: Checkout repository
        if: steps.check.outputs.needs-updating == 'true' || github.event.inputs.ignoreCommits == 'y'
        uses: actions/checkout@v3

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        if: steps.check.outputs.needs-updating == 'true' || github.event.inputs.ignoreCommits == 'y'
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        if: steps.check.outputs.needs-updating == 'true' || github.event.inputs.ignoreCommits == 'y'
        with:
          platforms: linux/${{ matrix.tag }}
          context: docker/openmower
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cedbossneo-${{matrix.tag}}
          labels: ${{ steps.meta.outputs.labels }}

